//#define TELEGRAM_DEBUG 1

#define HTTP_BUFFER_SIZE 10

#define MENU_STATE_COUNT 4

#define USER_CACHE_SIZE 30

#define RANDOM_PUNISHMENT_PROBABILITY 5

#define DEFAULT_SESSION_LENGTH 86400

#define UTC_OFFSET 1

#define TIME_MINIMUM 1800
#define TIME_MAXIMUM 7200

#define SLEEP_TIME_BEGIN 23
#define SLEEP_TIME_END 7

#define SHOCKS_PER_SESSION 50
#define SHOCK_BACKFILL_PROBABILITY 100
#define SHOCK_NEEDINESS_THRESHOLD 60.0
#define SHOCK_COUNT_MAXMIMUM 30
#define SHOCK_DURATION_MINIMUM 1000
#define SHOCK_DURATION_DEFAULT 2000
#define SHOCK_DURATION_MAXIMUM 20000
#define SHOCK_BREAK_DURATION 2000

#define UNLOCK_DURATION 4000

#define REQUIREMENTS_ENABLED false
#define REQUIREMENTS_REQUEST_MAX 20
#define REQUIREMENTS_LOCK_PER_SESSION 1000
#define REQUIREMENTS_REMOVAL_PROBABILITY 100

#define PILLORY_PROBABILITY 6
#define PILLORY_MINIMUM 1800
#define PILLORY_MAXIMUM 7200

// number of messages in history/reading
#define MESSAGE_HISTORY_SIZE 40
// length of a message summary entry (per message)
#define MESSAGE_SUMMARY_SIZE 60

#define NO_REPLY false
#define IS_REPLY true

#define FORCE true
#define OPTIONAL false
#define ONLY_NAME true
#define FULL false

// ---------------------------------

#define SSID1     "YOURSSID1"
#define PASSWORD1 "YOURPASSWORD1"
#define SSID2     "YOURSSID2"
#define PASSWORD2 "YOURPASSWORD2"
#define SSID3     "YOURSSID3"
#define PASSWORD3 "YOURPASSWORD3"

#define WEARER_NAME "EMLALOCK_WEARERUSERNAME"
#define WEARER_ID "EMLALOCK_WEARER_USER_ID"
#define WEARER_APIKEY "EMLALOCK_WEARER_APIKEY"

#define MISTRESS_NAME "EMLALOCK_SHOCKCELL_USERNAME"
#define MISTRESS_PASSWORD "EMLALOCK_SHOCKCELL_USERNAME"
#define MISTRESS_ID "EMLALOCK_SHOCKCELL_USER_ID"
#define MISTRESS_APIKEY "EMLALOCK_SHOCKCELL_APIKEY"

// ---------------------------------

#define SERVO_PIN 2
#define SHOCK_PIN 4
#define COVER_OPEN_PIN 15
#define COVER_OPEN 0
#define COVER_CLOSED 1

// ---------------------------------
// TELEGRAM

#define BOT_REQUEST_INTERVAL 1000
#define CHAT_ID "TELEGRAM_CHAT_ID"

// ---------------------------------
// CHASTIKEY

#define CHASTIKEY_USER_ID "CHASTIKEY_USER_ID"

//
